In [2]:
# Basic Numpy Array Info
import numpy as np

arr = np.array([[1, 2, 3], [4, 2, 5]])
print("Array is of type:", type(arr))
print("No of dimensions:", arr.ndim)
print("Shape of array:", arr.shape)
print("Size of array:", arr.size)
print("Array stores elements of type:", arr.dtype)


Array is of type: <class 'numpy.ndarray'>
No of dimensions: 2
Shape of array: (2, 3)
Size of array: 6
Array stores elements of type: int32


In [3]:
# Slicing Example
import numpy as np

a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
print(a)
print("After Slicing:")
print(a[1:])


[[1 2 3]
 [3 4 5]
 [4 5 6]]
After Slicing:
[[3 4 5]
 [4 5 6]]


In [4]:
# Advanced Indexing Example
import numpy as np

a = np.array([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
print('Our array is:')
print(a)

print('The items in the second column are:')
print(a[..., 1])  # all rows, column index 1

print('\nThe items in the second row are:')
print(a[1, ...])  # row index 1, all columns

print('\nThe items column 1 onwards are:')
print(a[..., 1])  # same as second column


Our array is:
[[1 2 3]
 [3 4 5]
 [4 5 6]]
The items in the second column are:
[2 4 5]

The items in the second row are:
[3 4 5]

The items column 1 onwards are:
[2 4 5]


In [7]:
import numpy as np
import pandas as pd

# Fixing the data structure
data = [
    ['Row1', 1, 2],
    ['Row2', 3, 4]
]

columns = ['Col1', 'Col2']
index = [row[0] for row in data]
values = [row[1:] for row in data]

df = pd.DataFrame(data=values, index=index, columns=columns)
print(df)


      Col1  Col2
Row1     1     2
Row2     3     4


In [8]:
# DataFrame from 2D array
my_2darray = np.array([[1, 2, 3], [4, 5, 6]])
print(pd.DataFrame(my_2darray))


   0  1  2
0  1  2  3
1  4  5  6


In [9]:
# DataFrame from dictionary
my_dict = {1: ['1', '3'], 2: ['1', '2'], 3: ['2', '4']}
print(pd.DataFrame(my_dict))


   1  2  3
0  1  1  2
1  3  2  4


In [10]:
# DataFrame from list with index and column
my_df = pd.DataFrame(data=[4, 5, 6, 7], index=range(0, 4), columns=['A'])
print(pd.DataFrame(my_df))


   A
0  4
1  5
2  6
3  7


In [11]:
# DataFrame from Series
my_series = pd.Series({
    "UnitedKingdom": "London",
    "India": "NewDelhi",
    "United States": "Washington",
    "Belgium": "Brussels"
})
print(pd.DataFrame(my_series))


                        0
UnitedKingdom      London
India            NewDelhi
United States  Washington
Belgium          Brussels


In [12]:
# Shape and length of DataFrame
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6]]))
print(df.shape)
print(len(df.index))


(2, 3)
2


In [13]:
import matplotlib.pyplot as plt

x = [1, 2, 3]
y = [2, 4, 1]

plt.plot(x, y)
plt.xlabel('x-axis')
plt.ylabel('y-axis')
plt.title('My first graph')
plt.show()
